### ISSUE TITLE
Missing fated BoE's

### ISSUE THREAD

**Issue by Sebastian1989101** [Trinovantes/WoWPay2Win#17]
Seems like all the Fated BoE's are missing? Or did I miss something?

**Comment by Trinovantes** [comment]
I haven't played the game in years so I don't keep up with game news. I'll look into this when I have time later since this doesn't seem like a simple item id update.

**Comment by Trinovantes** [comment]
Nevermind, it was actually just a simple item id update for me

Site is now updated
